/*
    AppManager.js - PWA management for ServiceWorker and PushNotification registration
    Copyright (c) 2018 Bence Skorka and CSFCloud. All rights reserved.
    https://github.com/SkorkaBence/WebSudoku
*/

var ServiceWorkerManager=function(a,b,c){this.updatecallback=a;this.push=null;this.public_key=c;this.sw=null;var d=this;"serviceWorker"in navigator&&(navigator.serviceWorker.register(b).then(function(a){d.pushupdate({type:"sw_register",status:"registered"});d.sw=a;"string"==typeof c&&d.updateStatus()},function(a){console.log("ServiceWorker registration failed: ",a);d.pushupdate({type:"sw_register",status:"failed"})}),window.addEventListener("beforeinstallprompt",function(a){a.userChoice.then(function(a){console.log(a.outcome);
    "dismissed"==a.outcome?(console.log("User cancelled home screen install"),d.pushupdate({type:"home_icon",status:"cancelled"})):(console.log("User added to home screen"),d.pushupdate({type:"home_icon",status:"added"}))})}))};ServiceWorkerManager.prototype.pushupdate=function(a){if("function"==typeof this.updatecallback)try{this.updatecallback(a)}catch(b){console.log("Callback error:",b)}};
    ServiceWorkerManager.prototype.updateStatus=function(){var a=this;this.sw.pushManager.getSubscription().then(function(b){a.isSubscribed=null!==b;a.isSubscribed?(console.log("[PUSH] User IS subscribed."),console.log(JSON.stringify(b)),a.pushupdate({type:"subscription_status",status:"subscribed",data:b})):(console.log("[PUSH] User is NOT subscribed."),a.pushupdate({type:"subscription_status",status:"not_subscribed"}))})};
    ServiceWorkerManager.prototype.subscribeUser=function(){var a=this,b=this.urlB64ToUint8Array(this.public_key);this.sw.pushManager.subscribe({userVisibleOnly:!0,applicationServerKey:b}).then(function(b){console.log("[PUSH] Subscription successfull");a.updateStatus()})["catch"](function(b){console.log("[PUSH] Subscription failed",b);a.updateStatus()})};
    ServiceWorkerManager.prototype.unsubscribeUser=function(){var a=this;this.sw.pushManager.getSubscription().then(function(a){if(a)return a.unsubscribe()})["catch"](function(a){console.log("Error unsubscribing",a)}).then(function(){a.updateStatus()})};ServiceWorkerManager.prototype.urlB64ToUint8Array=function(a){var b="=".repeat((4-a.length%4)%4);a=(a+b).replace(/\-/g,"+").replace(/_/g,"/");a=window.atob(a);b=new Uint8Array(a.length);for(var c=0;c<a.length;++c)b[c]=a.charCodeAt(c);return b};